language: android
before_install:
 - yes | sdkmanager "platforms;android-28"
 - yes | sdkmanager "build-tools;28.0.3"
 - chmod +x gradlew
script:
 - ./gradlew :NativeBlobDetector:clean :NativeBlobDetector:build
